# Generated by Django 5.2.8 on 2025-12-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rollno', models.IntegerField(unique=True)),
                ('math_marks', models.IntegerField()),
                ('science_marks', models.IntegerField()),
                ('english_marks', models.IntegerField()),
                ('history_marks', models.IntegerField()),
            ],
        ),
    ]
