# Generated by Django 5.2.8 on 2025-12-04 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_teacher', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentdetails',
            name='name',
        ),
        migrations.AddField(
            model_name='studentdetails',
            name='user',
            field=models.OneToOneField(default=1, limit_choices_to={'is_staff': False}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
